# Generated by Django 5.1.1 on 2024-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
