# Generated by Django 5.1.1 on 2024-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_aaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='aaluno',
            old_name='curso',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='aaluno',
            name='cpf',
        ),
        migrations.AddField(
            model_name='aaluno',
            name='nome_mae',
            field=models.CharField(default='Nao informado', max_length=100),
        ),
        migrations.AddField(
            model_name='aaluno',
            name='nome_pai',
            field=models.CharField(default='Nao informado', max_length=100),
        ),
    ]
