# Generated by Django 5.1.1 on 2024-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0004_cadastro_delete_acurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='titulo',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='login',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='login',
            name='logo',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(max_length=100),
        ),
    ]
