# Generated by Django 5.1.1 on 2024-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0005_rename_titulo_login_username_remove_login_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
    ]
