# Generated by Django 5.1.1 on 2024-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0006_acurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='acurso',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='acurso',
            name='turma',
        ),
    ]
