# Generated by Django 5.1.1 on 2024-10-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0007_aturma_remove_acurso_periodo_remove_acurso_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mural.acurso'),
        ),
    ]
