# Generated by Django 5.1.1 on 2024-10-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0009_remove_aturma_curso_acurso_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aturma',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
